### ISSUE TITLE
Installing with pip and running anvil-app-server produces this error

### ISSUE THREAD

**Issue by quesada** [Alcampopiano/OpenQuestion#1]
Using the install instructuions from the docs, on a virtual environment:

$ python3 -m venv tutorial-env
...
$ pip install openquestion
...
$ anvil-app-server --app OpenQuestion
Found Anvil App Server JAR in package directory
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:/home/q/prj/DSRonline/tutorial-env/lib/python3.9/site-packages/anvil_app_server/anvil-app-server.20210113-190622.jar) to constructor sun.security.provider.Sun()
WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
'OpenQuestion' does not contain an Anvil app.
Specify the app to serve with the --app option.

This is on manjaro linux using the system's python:
$python3 --version
Python 3.9.1

**Comment by Alcampopiano** [comment]
Hey there @quesada!

I hope you are well.

Could you try:
`pip install OpenQuestion` with the capital letters.

And then, please clone the app project itself with:
`git clone https://github.com/Alcampopiano/OpenQuestion.git`

From above that newly cloned project (a folder called OpenQuestion), you can try running the app server as you did before.

I will (and have been) smoothing out the installation process and so this will be made clearer in the near future.

**Comment by quesada** [comment]
> anvil-app-server --app OpenQuestion

That worked, thanks!
it takes me to a login page. There's an option to login with microsoft, but no sign up that I can see?

**Comment by Alcampopiano** [comment]
Currently you have add yourself (and/or your developers) as users using the shell. Please have a look at the [installation](https://alcampopiano.github.io/OpenQuestion/installation/) docs again. They describe how to drop into the Python shell and add users to the database.

There are also details in the [FAQ](https://alcampopiano.github.io/OpenQuestion/faq/#can-i-change-the-default-authentication-services-for-admins) regarding using different authentication services in case that is helpful.

Take care!
